### ISSUE TITLE
Error 'locales/ru-RU_readme.txt' cannot be found

### ISSUE THREAD

**Issue by T1MOXA** [TheJeterLP/ChatEx#13]
```
java.lang.IllegalArgumentException: The embedded resource 'locales/ru-RU_readme.txt' cannot be found in plugins/ChatEx.jar 
at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:202) 
at de.JeterLP.ChatManager.ChatEX.onEnable(ChatEX.java:36) 
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) 
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) 
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) 
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) 
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) 
at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) 
at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) 
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) 
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) 
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) 
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) 
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) 
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) 
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) 
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) 
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) 
at java.lang.Thread.run(Thread.java:745) 

```

**Comment by TheJeterLP** [comment]
That's because the Russian files were not up to date :)

Mit freundlichen Grüßen

Joey Peter

Am 03.06.2017 12:43 vorm. schrieb "T1MOXA" <notifications@github.com>:

**Comment by T1MOXA** [comment]
How to update ?

**Comment by TheJeterLP** [comment]
You would have to create a whole new Russian file and send it to me so I
can put it in the plugin and release a new version

Mit freundlichen Grüßen

Joey Peter

Am 03.06.2017 3:02 vorm. schrieb "T1MOXA" <notifications@github.com>:

**Comment by T1MOXA** [comment]
https://fex.net/940230131523
