### ISSUE TITLE
bug update chatex 1.16.1

### ISSUE THREAD

**Issue by iLiDanMoon** [TheJeterLP/ChatEx#27]
[12:17:53] [Async Chat Thread - #22/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatEx v2.5.7
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1068) ~[?:?]
	at java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[?:?]
	at java.util.regex.Matcher.replaceAll(Matcher.java:1182) ~[?:?]
	at java.lang.String.replaceAll(String.java:2126) ~[?:?]
	at de.jeter.chatex.utils.adManager.SimpleAdManager.checkForAds(SimpleAdManager.java:100) ~[?:?]
	at de.jeter.chatex.ChatListener.onChat(ChatListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor428.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-77]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-77]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-77]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-77]
	at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-77]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-77]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-77]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(

**Comment by TheJeterLP** [comment]
Fixed with PR #28
