### ISSUE TITLE
Could not pass event PlayerJoinEvent to ChatEx v2.6.1

### ISSUE THREAD

**Issue by JuniorGamer136** [TheJeterLP/ChatEx#40]
The plugin gives me an error in console:

[18:52:14 ERROR]: Could not pass event PlayerJoinEvent to ChatEx v2.6.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-ba75d9a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-ba75d9a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [server.jar:git-PaperSpigot-ba75d9a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:303) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:186) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:192) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:793) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:641) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:547) [server.jar:git-PaperSpigot-ba75d9a]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-PaperSpigot-ba75d9a]
Caused by: java.lang.IllegalArgumentException: Player list names can only be a maximum of 16 characters long
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:190) ~[server.jar:git-PaperSpigot-ba75d9a]
        at de.jeter.chatex.PlayerListener.onJoin(PlayerListener.java:44) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[server.jar:git-PaperSpigot-ba75d9a]
        ... 14 more

**Comment by worldOneo** [comment]
As you can see here: [Javadoc Bukkit 1.7 Player#setPlayerListName](https://jd.bukkit.org/org/bukkit/entity/Player.html#setPlayerListName(java.lang.String)) Bukkit 1.7 (and forks) is limited to 16 characters as a players list name.
I think your tablist format (Standard: `'%prefix%player%suffix'`) is longer than 16 characters, causing the error.
I belive a solution could be to disable your your tablist change in the config:
 ```yaml
 Tablist:
  Change: false
```
