### ISSUE TITLE
[BUG] PlaceholderAPI Doesn't loading

### ISSUE THREAD

**Issue by ZuVEnO** [TheJeterLP/ChatEx#50]
[21:52:19 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'chatex' in plugin ChatEx v2.7.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.IllegalArgumentException: Player list names can only be a maximum of 16 characters long
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:203) ~[CraftPlayer.class:1.7.10-1614.58]
        at de.jeter.chatex.CommandHandler.onCommand(CommandHandler.java:52) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
        ... 13 more
[21:52:20 INFO]: [G] UnknownZuVEnO [%battlelevels_level%]: 212

**Comment by TheJeterLP** [comment]
update to latest version.
