### ISSUE TITLE
Error (with PlaceholderAPI?)

### ISSUE THREAD

**Issue by Liam024** [TheJeterLP/ChatEx#6]
Hi!

Manchmal kriege ich den Fehler bei mir wenn jemand was schreibt:

```
[12:24:27] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatEx v2.4.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at de.jeter.chatex.utils.Locales.getString(Locales.java:54) ~[?:?]
	at de.jeter.chatex.ChatListener.onChat(ChatListener.java:31) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	... 11 more
```

Allerdings bei Servern ohne PlaceholderAPI geht es.

Ist die neuste Version (2.4.4) auf der 1.8.8

**Comment by TheJeterLP** [comment]
Schaue ich mir an, danke :)

**Comment by TheJeterLP** [comment]
Kannst du mir deine chatex config mal schicken?

**Comment by Liam024** [comment]
check-for-updates: true
bungeecord: false
message-format: '%prefix%player&8: &f%message'
global-message-format: '%prefix%player&8: &f%message'
multi-prefixes: false
multi-suffixes: false
ranged-mode: false
show-no-players-near: false
chat-range: -1
logChat: false
Locale: de-DE
Ads:
  Enabled: false
  Bypass:
  - google.de
  Log: true
AntiSpam:
  Seconds: 5
  Enable: false
BlockedWords:
- shit
Tablist:
  Change: false
  format: '%prefix%player%suffix'
Messages:
  JoinAndQuit:
    Enabled: false

**Comment by TheJeterLP** [comment]
Merkwürdig, da ist ja gar nichts von TabAPI drinnen, muss ich mir Mal
Genauer ansehen

Liam <notifications@github.com> schrieb am So., 19. Apr. 2020, 14:29:
