### ISSUE TITLE
[BUG] Error when launching the plugin

### ISSUE THREAD

**Issue by Baba0bab** [TheJeterLP/ChatEx#84]
**Describe the bug**
Error when launching the plugin

The plugin is not compatible with the Java version, it seems to me and therefore does not want to start

Error :
```
Could not load 'plugins/ChatEx-2.9.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: de/jeter/chatex/ChatEx has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:190) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]
Caused by: java.lang.UnsupportedClassVersionError: de/jeter/chatex/ChatEx has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_292]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_292]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_292]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_292]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_292]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_292]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_292]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_292]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_292]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[flamepaper.jar:git-PaperSpigot-"f6b10d47"]
	... 6 more
```

- OS: Debian 10
- Java Version : 8
- Minecraft Version : 1.8.8 (FlamePaper)
- ChatEx Version : 2.9.1

**Comment by TheJeterLP** [comment]
Update java to java > 16

**Comment by Baba0bab** [comment]
It's a pity before it worked perfectly with Java version 8

**Comment by TheJeterLP** [comment]
> It's a pity before it worked perfectly with Java version 8

Java 8 is way outdated. You should update it anyways

**Comment by TheJeterLP** [comment]
I just saw that you forked and compiled with java 8 again. What speaks against updating your java version?

**Comment by Baba0bab** [comment]
The other plugins I use and the version of Minecraft I use

**Comment by TheJeterLP** [comment]
> The other plugins I use and the version of Minecraft I use

They are backwards compatible. So they will still work

**Comment by Baba0bab** [comment]
I will try then, thank you
